### ISSUE TITLE
【Git】プルリクの運用について

### ISSUE THREAD

**Issue by YanagawaMasakazu** [YanagawaMasakazu/kanban#12]
> 開発用ブランチaaaでプルリク送ってレビュー待ちしている間、
> 開発用ブランチから別のブランチbbb(master以外)切って作業していたんですが、レビューの差し戻しが来て、急遽git checkoutして対応することになりましたが、この時先程の変更内容がmergeされてしまいました。

この状況を避けるために、以下のコマンドで凌いでいるのですが、この方法でよろしいでしょうか？
後、先輩方がこの状況に遭遇した時、どう対処しているのかお聞きしたいです。

```
git stash 　　　　//一度、変更内容を退避
git checkout aaa //aaaブランチにcheckout
git commit . -m "commit message" 
git push origin aaa
git checkout bbb //push後、bbbにcheckout
git stash pop //退避していた変更内容を取り出す
```

**Comment by MasakiSeino** [comment]
master -> aaa　と言う作業ブランチを切って、aaa -> bbb と言う作業ブランチを切った。
master に aaa  bbb と言う順番で merge してもらう予定が、bbb が先に master に merge された。
ってことであってる？

もしそうであるのなら、merge先を aaa にしておく、プルリの詳細の方にその旨を記載しておくとかかな。（記載例：前提プルリクとして #7  ）
あとは、labelsにWIPってのを作成してそのlabelをつけておくとかかな。
もしかりに上記のような状態になってるとしたら、bbbには変更内容にaaaの内容も含まれてる状態でのレビュー依頼がきてる形になる。だからもうすでにmasterにはaaaの内容も含まれた状態になってるはず。

**Comment by YanagawaMasakazu** [comment]
> master に aaa bbb と言う順番で merge してもらう予定が、bbb が先に master に merge された。
ってことであってる？

すみません、mergeって言葉使ってしまったので、分かりづらかったですね...

一応、ローカルリポジトリ内の話で、
master -> aaa　と言う作業ブランチを切って、aaa -> bbb と言う作業ブランチを切った。
→修正するために、git checkoutでブランチをaaaに戻す→bbbの変更が適用されてしまった。
という意味で記述しました。

**Comment by MasakiSeino** [comment]
あ〜そう言う話ね。
それってただbranch移動したけど、ファイルの更新がされてなくてそれで保存した結果その内容が含まれたってことでいいのかな？多分

梁川くんにも確認なんだけど、add ってどうやってる？

**Comment by MasakiSeino** [comment]
コマンドの話ね。
git add .
git add -p
git add -u
git add -a
結構いろいろオプションがあるけどどれ使ってる？

**Comment by YanagawaMasakazu** [comment]
そうですね。それで悩んでました。
最初に`git add .`してます。

**Comment by MasakiSeino** [comment]
git add . だと、ローカルの現在の変更内容全てをってなるから関係ない内容が含まれてる状態でコミットしてしまう可能性があるから git add -p で add する内容を確認しつつ、した方がいいと思うよ。
そうすれば上記のような時に、変更差分を確認しながらaddするからなんか関係ないような内容があるぞって気がつくし

**Comment by YanagawaMasakazu** [comment]
分かりました。今度から使ってみます！
