### ISSUE TITLE
【ご質問】メソッド名や変数名の名前付けについて

### ISSUE THREAD

**Issue by YanagawaMasakazu** [YanagawaMasakazu/kanban#17]
https://github.com/YanagawaMasakazu/kanban/pull/13 のプルリクについて、
メソッド名と変数名の付け方があまり理解していないので、
メソッド名の変数名の名前の付け方についてお聞きしたいです。

【お聞きしたい事】
- メソッド名や変数名の適切な名前の付け方を知りたい
- やってはいけない名前の付け方も知りたい(予約語など基本的な物ではなく、https://github.com/YanagawaMasakazu/kanban/pull/13#discussion_r434400438 のような感じパターンを教えて欲しいです)

**Comment by Yamasou** [comment]
私もネーミングセンスがない & ベストの方法を知っているわけではないので
私が気をつけていることを共有しておきます

* メソッド名が処理内容を説明できているか
* 英文的におかしくないか
* 使用している言語の慣習に沿ってるか
* あと感覚

**Comment by YanagawaMasakazu** [comment]
@Yamasou 
ありがとうございます。
あまり意識していない所でしたので、勉強になります。

**Comment by Yamasou** [comment]
ほんとはもっと意識したほうがいいことあると思うのですが、
いまぱっと思いついたのがこんな感じです。
『リーダルブルコード』という本を本屋さんで立ち読みして得た知識です。

**Comment by YanagawaMasakazu** [comment]
@Yamasou 
リーダルブルコード持ってるんですが、積読しちゃってました.....
今すぐ読もうと思います。

**Comment by Yamasou** [comment]
言うて私は立ち読みしただけなので冒頭なんページかくらいしか読んでいない

**Comment by YanagawaMasakazu** [comment]
> 言うて私は立ち読みしただけなので冒頭なんページかくらいしか読んでいない

立ち読みでインプット出来てるのすごいです....

-----------
https://github.com/YanagawaMasakazu/kanban/pull/13#discussion_r434400438
↑今、こちらの修正しているのですが、メソッドの役割考えると冒頭にgetつければ良いかなと思ったんですが、いかがでしょうか？

```
  methods: {
    getMailData(value) {
      this.email = value
      console.log(value)
    },
    getPasswordData(value) {
      this.password = value
      console.log(value)
    }

```

**Comment by qrg** [comment]
@Yamasou @YanagawaMasakazu 
リーダブルコードはバイブルなので全力おすすめ祭りです

**Comment by Yamasou** [comment]
処理を見ると
this の email に value を入れている
( this -> vue インスタンス )

なのでどちらかといえば set とかそっちの方面ではないかと
get は取得とかなので

**Comment by YanagawaMasakazu** [comment]
@Yamasou 

> 処理を見ると
> this の email に value を入れている
> ( this -> vue インスタンス )
> 
> なのでどちらかといえば set とかそっちの方面ではないかと
> get は取得とかなので

なるほどです。
ちゃんと、処理を言語化する能力も必要ですね。

**Comment by YanagawaMasakazu** [comment]
大体の知見が得られたので、closeしようと思います。

**Comment by YanagawaMasakazu** [comment]
【メモ】
リーダブルコード読む
